# Generated by Django 5.1.4 on 2024-12-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_listened_alter_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='title',
            new_name='name',
        ),
    ]
